server:
    port: 8080    
    servlet:
        contextPath: /api/v2/billing

spring:  
    main:
        allow-bean-definition-overriding: true
    application:
        name: "comerzzia api v2 billing"
    messages:
        basename: i18n/messages,i18n/custom-messages
    jackson:
       serialization:
          FAIL_ON_EMPTY_BEANS: false
        
management:
  server:
    port: 8081
  endpoint:
    prometheus:
      enabled: true      
  metrics:
    export:      
      prometheus:
        enabled: true             
  endpoints:
    web:
      base-path: "/manage"        
      exposure:
        include: "*"
                  
logging:
    level:
        ROOT: INFO        
        com.comerzzia.api: DEBUG
        com.comerzzia.custom.api: DEBUG
        org.mybatis: INFO   
        org.springframework : INFO     